version: '3.9'

services:
  db:
    image: postgres:17.2
    container_name: goit-py_web-hw-06
    environment:
      POSTGRES_USER: myDB    
      POSTGRES_PASSWORD: 12345  
      POSTGRES_DB: postgres     
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  postgres_test_data:
